# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

AdminPermission: telepads.admin

# Command settings
PortableTelepadCommand:
  permission: "telepads.commands.portabletelepad"
  aliases:
    - pad
GiveBuildItem:
  permission: "telepads.commands.givetlelepaditem"
  aliases:
    - giveteleitem

UseTelepadCost: 2
UpgradeCost: 200

#Teleport(TPA and RTP) logic:
TPA:
  AutoCancleInSeconds: 300
  DontMoveTimeInSeconds: 3

Teleport:
  MoveTolerance: 1.5
