# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

AdminPermission: telepads.admin

# Command settings
PortableTelepadCommand:
  permission: "telepads.commands.portabletelepad"
  aliases:
    - pad
GiveBuildItem:
  permission: "telepads.commands.givetlelepaditem"
  aliases:
    - giveteleitem
ReloadCommand:
  permission: "telepads.commands.reload"

Messages:
  dbError: <red>Es gab einen Fehler beim erstellen des Telepads in der Datenbank, bitte kontactiere einen Administrator!</red>"
  createTelepad: "<green>Dein Telepad wurde erstellt.</green>"  
  regex: "<red>Dieser Name ist ungültig <br>Der Name darf nur die Zeichen [a-zA-Z0-9_ </>] verwenden <br> und muss zwischen 3 und 32 Zeichen lang sein.</red>"
  invFull: "<red>Dein Inventar ist voll, bitte lerre es um das Telepad aufzusammeln</red>"
  pickup: "<green>Du hast das Telepad erfolgreich augehoben.</green>"
  exitChatInput: "Abgebrochen"
  upgraded: "Dein Telepad wurde aufgewertet."
  maxLevel: "<red>Dein Telepad hat bereits das maximale Level!</red>"
  pickupRegainMoney: "Dir wurden <green>200 Coins</green> gutgeschrieben."
  # Placeholder: <name>
  renameTelepad: "Dein Telepad wurde \"<name>\" genannt."
  fullInventory: "<red>Dein Inventar ist voll, bitte lerre es um das Telepad aufzusammeln</red>"
  pickup: "<green>Du hast das Telepad erfolgreich augehoben.</green>"
  levelup: "Dein Telepad wurde aufgewertet."
  addPermission: "Der Spieler \"<green><name></green>\" wurde für dieses Telepad gesetzt."
  removePermission: ""
  blocknotFound: "<red>Dieser Block wurde nicht gefunden.</red>"
  changesBlock: "Dein Telepad Block wurde zu \"<green><name></green>\" geändert."
  # This ussually happens when a telepad is right klicked which is not in the databse (example: DB reset, )
  errorSupport: "Ein fehler ist aufgetreten, bitte melde dich im support."
  # Placeholder: <desti>
  setDestination: "Du hast \"<desti>\" erfolgreich als Ziel gesetzt."

UseTelepadCost: 2
TelepadGUI:
  levelup:
    name: "Aufwerten"
    cost: 200
  customizer:
    blocktype:
      question: "Welcher soll dein neuer Anzeige Block sein?.<br>Schreibe \"exit\" oder \"abbrechen\" um den Vorgang abzubrechen."
      exitWords:
        - "exit"
        - "abbrechen"
    telepadname:
      question: "Wie möchtest du dein Telepad nennen?.<br>Schreibe \"exit\" oder \"abbrechen\" um den Vorgang abzubrechen."
      exitWords:
        - "exit"
        - "abbrechen"
  publicity:
    list:
      removePlayer:
        name: "Klicke um zu entfernen."
    add:
      question: "Schreibe den Spielernamne den du hinzufügen willst in den Chat.<br>Schreibe \"exit\" zum abzubrechen."
      exitWords:
        - exit
        - abbrechen

#Teleport(TPA and RTP) logic:
TPA:
  AutoCancleInSeconds: 300
  DontMoveTimeInSeconds: 3

Teleport:
  MoveTolerance: 1.5