name: Telepads
version: "${version}"
main: de.jonas.telepads.Telepads
description: Telepads
api-version: "1.21.4"
authors:
  - "Jon1Games"
  - "gkram"
loader: de.jonas.telepads.Telepadloader
dependencies:
  server:
    Stuff:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    ConfigAPI:
      load: BEFORE
      required: true
      join-classpath: true
