name: Telepads
version: '${version}'
main: de.jonas.telepads.Telepads
description: Telepads
api-version: '1.20'
authors:
  - "Jon1Games"
  - "gkram"
dependencies:
  server:
    Stuff:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true